### PR TITLE
Update the Firefox icon

### PR DESCRIPTION
**Pull request by mgol**
Firefox 70 has changed the icon.

I copied the new icon from https://github.com/alrra/browser-logos.

### CODE REVIEW

**Comment by mgol** [comment]
cc @Krinkle

**Comment by mgol** [comment]
Screen Shot 2019-11-02 at 16 50 03

**Comment by mgol** [comment]
The Travis failures look unrelated.

**Comment by alrra** [comment]
@mgol @Krinkle Any plans to [automate this step](https://github.com/jquery/testswarm/pull/317)? (e.g.: see: https://github.com/whatwg/whatwg.org/pull/265)

**Comment by mgol** [comment]
@allra I’d be OK with automating this but see https://github.com/jquery/testswarm/pull/317#issuecomment-473719706.

PRs welcome. :)

**Pull request merged**
