### PR TITLE
Update browser icons

### PR DESCRIPTION
**Pull request by mgol**
The biggest change is in the Firefox icon but others have changed slightly
as well.

### CODE REVIEW

**Comment by mgol** [comment]
cc @Krinkle

**Comment by mgol** [comment]
I've noticed GitHub doesn't show the icons before/after so I'm pasting screenshots below:

screen shot 2018-12-19 at 23 06 03
screen shot 2018-12-19 at 23 06 23
screen shot 2018-12-19 at 23 06 35
screen shot 2018-12-19 at 23 06 49
screen shot 2018-12-19 at 23 06 56

**Comment by Krinkle** [comment]
@mgol I assume the browser logos come from <https://github.com/alrra/browser-logos>, but what about the device images?

**Comment by mgol** [comment]
I didn't know about https://github.com/alrra/browser-logos, I actually found those graphics on the internet, most often from Wikipedia (after manual rescaling). 😅 Should I swap them?

As for the identical logos, I wanted to remove the mobile ones but I didn't fully follow the logic, in particular what makes Firefox accept the `_mobile` suffix while Chrome requires `_android`. Could you explain that to me?

**Comment by Krinkle** [comment]
For User-Agent string related information, TestSwarm uses the [UAParser](https://github.com/ua-parser/uap-php) project (which reads [uap-core:/regexes](https://github.com/ua-parser/uap-core/blob/010ccdc7303546cd22b9da687c29f4a996990014/regexes.yaml). That file maps a User-Agent string to a browser family, device family and OS family with version numbers.

This is used by TestSwarm in the localSettings configuration for browser presets, at run-time when handing out pending tests from the database to connected clients, and for the rendering of these icons on the home page and on results pages!

Our call and HTML template resides in [the BrowserInfo class (src)](https://github.com/jquery/testswarm/blob/c420076142d9e9fd0918fd9bf35fc8db6eeaaa04/inc/BrowserInfo.php#L181). 

In [testswarm.css](https://github.com/jquery/testswarm/blob/c420076142d9e9fd0918fd9bf35fc8db6eeaaa04/css/testswarm.css#L453) multiple selectors are added to the same rule to share the logo file. In most cases we share 1 logo for the entire family regardless of version, but in some cases (old IE) we have separate logos per logo as well. Likewise, there are also cases where multiple families share the same logo   (e.g. desktop/mobile safari).

**Comment by Krinkle** [comment]
I've re-updated the browser icons from browser-logos. I couldn't see any difference except that they were slightly more optimised, and the padding around the Chrome logo was different (matches the padding from the previous one, for consistency).

The device/os logos I ran through ImageOptim before merging.

**Comment by mgol** [comment]
Thank you, @Krinkle!

**Comment by alrra** [comment]
> i've re-updated the browser icons from browser-logos. 

@Krinkle, @mgol Note: [You can get the browser logos using `npm`](https://www.npmjs.com/org/browser-logos). 

> slightly more optimised

Yes, they will be up-to-date and highly optimized (e.g.: [1](https://github.com/alrra/browser-logos/blob/88a8230471acab9d490c730be560f16167580525/src/chrome/CHANGELOG.md#105-march-8-2019), [2](https://github.com/alrra/browser-logos/blob/88a8230471acab9d490c730be560f16167580525/src/firefox/CHANGELOG.md#201-march-8-2019), etc.).

**Comment by mgol** [comment]
@alrra Thanks for the info. TestSwarm currently doesn't have any `dependencies` so this would have to be coupled with something like [grunt-npmcopy](https://www.npmjs.com/package/grunt-npmcopy) (it could be implemented manually via npm scripts as well).

**Pull request closed without merging**
