### PR TITLE
BrowserInfo: Update the Opera icon

### PR DESCRIPTION
**Pull request by mgol**
The current one is quite old!

### CODE REVIEW

**Comment by Krinkle** [comment]
🚢 Deployed.

**Comment by mgol** [comment]
@Krinkle I'm still a bit confused how to reset caches here. The new Edge icon started working when I opened `/api.php?action=cleanup` but that doesn't seem to help here, http://swarm.jquery.org/img/browser-opera.png still shows the old icon while http://swarm.jquery.org/img/browser-opera.png?x shows the new one.

How to reliably clear image cache?

**Comment by Krinkle** [comment]
No, they are cached by the Cloudflare CDN.

```
ETag: "5e288486-1675"
Cache-Control: public, max-age=86400
CF-Cache-Status: HIT
Age: 1365
…
Expires: Thu, 23 Jan 2020 17:44:26 GMT
```

Depending on which CDN server is closest to you, it will be at a different point in the 86400-Age cycle.

For resources that have logical dependencies, we use a query string to explicitly version the resource. I didn't do that for the images as it seemed fine to roll over in 24h.

**Comment by mgol** [comment]
Ah, if it's going to refresh in 24h then that's totally fine, I agree. Thanks for the info!

**Pull request merged**
